# Generated by Django 2.0.1 on 2018-02-22 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0003_ability_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ability',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='ability',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='rpg.Character'),
        ),
        migrations.AlterField(
            model_name='character',
            name='class_name',
            field=models.CharField(max_length=100, verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='character',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='rpg.Game'),
        ),
        migrations.AlterField(
            model_name='item',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rpg.Character'),
        ),
    ]
