# Generated by Django 2.0.2 on 2018-02-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0004_auto_20180222_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='class_name',
            field=models.CharField(max_length=100),
        ),
    ]
