# Generated by Django 2.0.2 on 2018-02-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0006_character_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='avatar',
            field=models.URLField(blank=True, default='', max_length=400),
        ),
    ]
