# Generated by Django 2.0.2 on 2018-02-28 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0007_auto_20180225_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
